
tittle: PreetaM Gupta # your name (or website title) here
logo: "/profile.pnh?raw=true" # your photo (or logo) here
description: > #your tezt below (remove <br> elements if you don't need line breaks)
Computer Science Engineering Student
 <br><br>
 <a href="https://www.gihub.com/preetamguptas.com/preetamguptas/">Gihub</a>
theme: jekyll-theme-minimal
